server:
  port: 8080
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
      url: ${S3_URL}
    credentials:
      access-key : ${ACCESS_KEY}
      secret-key : ${SECRET_KEY}
    region:
      static: ${REGION}
      auto: false
    stack:
      false
api:
  ai-server: ${AI_SERVER_ADDRESS}